### ISSUE TITLE
Custom DataFusion branch?

### ISSUE THREAD

**Issue by jonmmease** [nevi-me/datafusion-rdbms-ext#4]
Hi @nevi-me, I wanted to reach out and let you know that I'd be interested in collaborating on this project/idea if it's something that's still of interest to you.

As background, I'm using DataFusion to power my [VegaFusion](https://vegafusion.io/) project.  I'm largely taking Vega specifications and compiling them into DataFusion `Expr`s and `LogicalPlan`s (bypassing SQL).  This works really well for evaluating computations in DataFusion, but I'm very interested in working out a way to optionally push supported computations into external databases.  And from what I can tell, that looks like exactly the kind of thing you're exploring here.

Do you have your custom DataFusion branch (with `TableSource`) pushed anywhere so that I could try compiling the `origins` branch of this project?
Thanks!

**Comment by nevi-me** [comment]
Hey @jonmmease, thanks for reaching out. I've dumped the code on my local machine into the main branch, and pushed the `TableSource` change to a branch on the DataFusion repo.

Please feel free to either fork the project, or let me know if you'd like write access.
If the project seems feasible, a good idea could be for us to donate it to the datafusion-contrib GH org so it's visible to more people.

I'll have a look at VegaFusion to see what interesting stuff you're doing there.

**Comment by jonmmease** [comment]
> Hey @jonmmease, thanks for reaching out. I've dumped the code on my local machine into the main branch, and pushed the `TableSource` change to a branch on the DataFusion repo.

Perfect, thanks!  I'll start playing around with it.  And yeah, if something useful comes out of it then I'd be interested in moving it to datafusion-contrib.

**Comment by nevi-me** [comment]
Here's a copy of the data that's in testdata/data https://drive.google.com/file/d/11OpwV_Sb3t07oUCLftgIEPcgf7jImOv-/view?usp=sharing. Sharing it in case it's easier to download it than generating the TPC-H data. I can't remember what process I used to generate the data.

**Comment by jonmmease** [comment]
Thanks @nevi-me, it looks like that link is restricted so I sent a "request access" message.

**Comment by jonmmease** [comment]
Thanks!  I think I got everything setup now, and the `pushdown_joins.rs` test is passing
